'use strict';
// Plain-text extraction for the AI knowledge base. Phase 1 supports the two
// formats SOPs/guides/policies actually show up in: PDF and plain text.
// DOCX/CSV/Excel ingestion is a deliberate fast-follow, not implemented here.
//
// Uses pdf-parse v2's PDFParse class (modern pdfjs-dist under the hood).
// The v1.x API (`pdfParse(buffer)`) was tried first and rejected: 1.1.1 is a
// 2018 release bundling a pdf.js from the same era, and it throws
// "bad XRef entry" on ordinary, structurally-valid PDFs — including ones
// generated by this very app via pdfkit. See __tests__/ai.textExtract.test.js,
// which parses a real generated PDF end-to-end specifically so a broken
// parser can never ship silently again.

const logger = require('../logger');

const SUPPORTED_MIME_TYPES = ['application/pdf', 'text/plain'];

/**
 * Extracts plain text from a document buffer. Throws a descriptive error for
 * unsupported types rather than silently returning empty text — an ingested
 * "document" with no content would otherwise sit as a permanently-empty,
 * confusing entry in the knowledge base.
 */
async function extractText(buffer, mimeType) {
  if (mimeType === 'application/pdf') {
    // Lazy-required: pulls in a full PDF.js runtime that's only needed here.
    const { PDFParse } = require('pdf-parse');
    let parser;
    try {
      parser = new PDFParse({ data: new Uint8Array(buffer) });
      const result = await parser.getText();
      return (result?.text || '').trim();
    } catch (err) {
      logger.warn({ err: err.message }, 'ai_knowledge_pdf_parse_failed');
      throw new Error(`Could not read this PDF (${err.message}). It may be password-protected or corrupted.`);
    } finally {
      // Releases the worker/document handles. Without this, ingesting many
      // documents in one process leaks them.
      if (parser) await parser.destroy().catch(() => {});
    }
  }

  if (mimeType === 'text/plain') {
    return buffer.toString('utf8').trim();
  }

  throw new Error(`Unsupported file type: ${mimeType}`);
}

module.exports = { extractText, SUPPORTED_MIME_TYPES };
